In [251]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


In [252]:
import numpy
arr = numpy.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [253]:
import numpy as np
arr1 = np.max([1,2,3,4,5])
print(arr1)

5


In [254]:
import numpy as np
arr = np.mean([1,2,3,4,5,6,7,8,9])
arr1 = np.std([2,4,5,6,7,8,9])
print("mean",arr)
print("std:",arr1)


mean 5.0
std: 2.2314999074019015


In [255]:
print(np.__version__)


2.4.6


In [256]:
# 1. Create an array of 5 integers and display all elements
import numpy  
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [257]:
#2. Store 10 numbers in an array and print them in reverse order
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1[10::-1])

[10  9  8  7  6  5  4  3  2  1]


In [258]:
# 3. Find the sum of all elements in an array
import numpy as np
a = np.array([1,2,3,4,5])
print(sum(a))

15


In [259]:
# 4.Find the average of array elements.
import numpy as np
arr = np.array([18,34,6,83,10,9,11,8])
a = sum(arr)
avg = a / len(arr)
print(len(arr))
print(a)
print(avg)

8
179
22.375


In [260]:
# 5. Find the maximum element in an array.
import numpy as np
arr = np.array([10,23,4,67,2,100])
print(max(arr))

100


In [261]:
# 6. Find the minimum element in an arr
import numpy as np
arr1 = np.array([12,34,6,3,0,45,31,9,2,11])
print(min(arr1))

0


In [262]:
# 7.Count the number of even and odd elements in an array
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8,9])
for arr1 in arr:
    if arr1 % 2==0:
        print("even num:",arr1 )
    else:
        print("Odd num:",arr1)

Odd num: 1
even num: 2
Odd num: 3
even num: 4
Odd num: 5
even num: 6
Odd num: 7
even num: 8
Odd num: 9


In [263]:
# 8. Search for a given element in an array.
import numpy as np
arr = np.array([21,4,67,30,15,45])
print(arr[4])

15


In [264]:
# 9. Count the occurrences of a specific element in an array.......
import numpy as np
arr = np.array([12,13,45,16,39,91,34,14,53,23,66,78])
print(arr)

[12 13 45 16 39 91 34 14 53 23 66 78]


In [265]:
# 10. Copy all elements from one array to another.......
import numpy as np
arr = np.array([1,2,3,4])
original = arr.copy()
print(a)

179


In [266]:
# 11. Merge two arrays into a third array.
import numpy as np 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr = np.concatenate((arr1,arr2))
# print(arr1.conjugate(arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [267]:
# import numpy as np
type(arr)

numpy.ndarray

In [268]:
# 12. Remove duplicate elements from an array
import numpy as np 
arr = np.array([1,2,3,4,5,1,2,3,4,5,1,2,3,4,5])
a = np.unique(arr)
print(a)

[1 2 3 4 5]


In [269]:
# 13.Sort an array in ascending order.
import numpy as np
arr = np.array([3,4,1,18,5,9,0,2,11,7,6,12])
a = np.sort(arr)
print(a)

[ 0  1  2  3  4  5  6  7  9 11 12 18]


In [270]:
# 14.Sort an array in descending order.
import numpy as np
arr = np.array([7,0,1,14,11,6,8,6,12,4])
a = np.sort(arr)[::-1]
print(a)

[14 12 11  8  7  6  6  4  1  0]


In [271]:
# 15. Find the second largest element in an array............

import numpy as np
arr = np.array([12,4,8,9,10,3,8,9,5,2])

# larges = arr[0]
# second = arr[0]

# for num in arr:
#     if num > larges:
#         second = larges
#         larges = num
#         print(num)
#     elif num > second and num !=larges:
#         second = num
# print(second)

'''<========= second method==========>'''
sort = np.sort(arr)
print(sort)
print(sort[-2])


[ 2  3  4  5  8  8  9  9 10 12]
10


In [272]:
# 16. Create a 3×3 matrix and display all elements
import numpy as np 
arr = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [273]:
# only copy element
import numpy as np
arr = np.array([1,2,3,4,5])
# print(arr)
a = arr.copy()
a[0] = 20
print(a)
print(arr)

[20  2  3  4  5]
[1 2 3 4 5]


In [274]:
# viwe cheng original valiue  
import numpy as np
arr =np.array([1,2,3,4])
original = arr.view()
original[3] = 99
print(original)
print(arr)

[ 1  2  3 99]
[ 1  2  3 99]


In [275]:
# 17.Find the sum of all elements in a matrix
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
print(sum(arr1))

[5 7 9]


In [276]:
# 18.Find the maximum element in a matrix
import numpy as np
arr1 = np.array([34,50,78,99,10,112,34,56,-34])
print(max(arr1))

112


In [277]:
# 19.Find the minimum element in a matrix.
print(min(arr1))

-34


In [278]:
# 20.Find the sum of each row in a matrix.
import numpy as np 
array = np.array([[5,9,7],[10,8,5],[8,6,9],[3,8,6]])
print(sum(array))

[26 31 27]


In [279]:
# 21.Find the sum of each column in a matrix  row----->, colum 
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
a = np.stack((arr),axis=1)
print("sum of row : ",sum(a))
print("sum of column:",sum(arr))

sum of row :  [10 26]
sum of column: [ 6  8 10 12]


In [280]:
# 22.Find the sum of the main diagonal elements.
import numpy as np 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
sum_diagonal = 0
for i in range(len(arr)):
    sum_diagonal += arr[i][i]
    print(sum_diagonal)
    
print("\nsum of diagonaml:",sum_diagonal)

1
6
15

sum of diagonaml: 15


In [281]:
# 23.Check whether a matrix is symmetric or not

arr = np.array([
    [1,2,3],
    [2,4,5],
    [3,5,6]
])
symmetric = True
for i in range(len(arr)):
    for j in range(len(arr)):
        if arr[i][j] != arr[j][i]:
            symmetric = False
            break
if symmetric:
    print("Matrix is symmetric")
else:
    print("Metric is not symmetric")


Matrix is symmetric


In [282]:
# 24.Check whether a matrix is symmetric or not.

import  numpy as np 
arr = np.array([
    [1,2,3],
    [2,4,5],
    [3,5,6]
])
symmetric = True
for i in range(len(arr)):
    for j in range(len(arr)):
        if arr[i][j] != arr[j][i]:
            symmetric = False
if symmetric:
    print("Matric is symetric.")
else:
    print("Matric is nor symmetric")

Matric is symetric.


In [283]:
# 25. Create a 3D array of size 2×2×2 and display all elements.

arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr.ndim)
print(arr.shape)


3
(2, 2, 2)


In [284]:
# 26.Find the sum of all elements in a 3D array

import numpy as np
array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array.ndim)
print(np.sum(array))

3
78


In [285]:
# 27.Find the maximum element in a 3D array
arr = np.array([[[23,4,7],[10,54,36]],[[10,55,22],[90,100,0]]])
print(np.max(arr))

100


In [286]:
# 28. Find the minimum element in a 3D array

print(np.min(arr))

0


In [287]:
# 29.Count the total number of elements in a 3D array.
print(arr.size)

12


In [288]:
# 30.Find all duplicate elements in an array

array = np.array([10,20,30,20,10,50,10])

duplicat = []
for i in range(len(array)):
    for j in range(i + 1, len(array)):
        if array[i] == array[j] and array[i] not in duplicat:
            duplicat.append(array[i])
            
print("Duplicate element: ",duplicat)


Duplicate element:  [np.int64(10), np.int64(20)]


In [289]:
# 31.Find all unique elements in an array.
import numpy as np
arr1 = np.array([12,3,5,12,5,9,8,12,7,8,9,3])
a = np.unique(arr1)
print(a)

[ 3  5  7  8  9 12]


In [290]:
# 32. Rotate an array to the left by one position.
""" position roted karva mate  = np.roll    
<===== left = -1, -2 ============>"""

arr = np.array([[[23,4,7],[10,54,36]],[[1,55,22],[90,100,0]]])
result = np.roll(arr, -1) 
# result = np.roll(arr, -2)
print(result)

[[[  4   7  10]
  [ 54  36   1]]

 [[ 55  22  90]
  [100   0  23]]]


In [291]:
# 33.Rotate an array to the right by one position
"""< ====== rigth = 1,2,3.. ===========>  """

result =  np.roll(arr, 2)
print(result)

[[[100   0  23]
  [  4   7  10]]

 [[ 54  36   1]
  [ 55  22  90]]]


In [292]:
# 34. Rotate an array by N positions
n = 3
num  = np.roll(arr, -n)
print(num)

[[[ 10  54  36]
  [  1  55  22]]

 [[ 90 100   0]
  [ 23   4   7]]]


In [293]:
# 35. Find the frequency of each element in an array.

arr = np.array([1,2,3,1,2,3,1,2,3,4,5,4,5,4,5,4,4,5,45,4,1,5,45])
element , frequency = np.unique(arr, return_counts=True)
print("element",element)
print("frequency",frequency)


element [ 1  2  3  4  5 45]
frequency [4 3 3 6 5 2]


In [294]:
# 36. Find the third largest element in an array.

arr = np.array([3,5,8,23,11,12,30,45,67])
sort = np.sort(arr)
print(sort)
print(sort[-3])

[ 3  5  8 11 12 23 30 45 67]
30


In [295]:
# 37. Reverse an array without using another array.

print(arr[::-1])

[67 45 30 12 11 23  8  5  3]


In [296]:
# 38. Insert an element at a specific position in an array.
arr = np.array([3,5,8,23,11,12,30,45,67])
a = np.insert(arr, 3, 0)
print(a.ndim)
print(a)

array = np.array([[1,2,3],[4,5,6]])
insert = np.insert(array, 2,10)
print(insert)
print(insert.ndim)

1
[ 3  5  8  0 23 11 12 30 45 67]
[ 1  2 10  3  4  5  6]
1


In [297]:
# 39. Delete an element from a specific position in an array
delet = np.delete(arr, 2)
print(delet)

[ 3  5 23 11 12 30 45 67]


In [298]:
# 40. Find the intersection of two arrays 
# Comman two number
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
arr = np.intersect1d(arr1, arr2)
print(arr)

[3 4 5]


In [299]:
# 41. Find the union of two arrays.
array  = np.union1d(arr1,arr2)
print(array)

[1 2 3 4 5 6 7]


In [300]:
# 42.Check whether two arrays are equal.

a1 = np.array([1,2,3,4,5])
a2 = np.array([1,2,3,4,5])
a3 = np.array([1,2,3,4,5,6,7])
a = np.array_equal(a1,a2)
print("Tow array equal =",a)
print(np.array_equal(a1,a3))


Tow array equal = True
False


In [301]:
# 43. Split an array into two equal halves.
import numpy as np
arr = np.array([11,22,33,44,55,66,77])
half = len(arr)//2
firs_half = arr[:half]
print(firs_half)
print(arr[half:])

[11 22 33]
[44 55 66 77]


In [302]:
# 44.Find all pairs whose sum equals a given number.

arr = np.array([1,2,3,4,5,6])
target = 9
for i in range(len(arr)):
    for j in range(len(arr)):
        if arr[i] + arr[j] == target:
            print(arr[i] , arr[j])

3 6
4 5
5 4
6 3


In [303]:
# 45. Find the missing number from an array containing 1 to N.
import numpy as np
arr = np.array([1,4,7,9,3,5,6])
n = 8
total = n * (n+1)//2
mising = total - np.sum(arr)
print(total)
print(mising)

36
1


In [304]:
# 46. Move all zeros to the end of the array
import numpy as np
arr = np.array([0,3,6,0,1,0,2,0,4])

non_zero = arr[arr != 0]
zero = arr[arr == 0]
result = np.concatenate((non_zero, zero))
print(result)

[3 6 1 2 4 0 0 0 0]


In [305]:
# 47. Separate positive and negative numbers in an array.
import numpy as np 
arr = np.array([1,-3,9,8,-5,-7,-4,-1,5,3])
neg = arr[arr <= 0]
pos = arr[arr > 0]
print("Negetive num:", neg)
print("Position num:" , pos)
# for a in arr:
#     if a < 0:
#         print(a, end=" ")



Negetive num: [-3 -5 -7 -4 -1]
Position num: [1 9 8 5 3]


In [306]:
# 48. Find the longest increasing sequence in an array......
arr = [1, 2, 3, 2, 4, 5, 6]
longest = []
current = [arr[0]]
for i in range(1, (len(arr))):
    if arr[i] > arr[i-1]:
        current.append(arr[i])
    else:
        if len(current) > len(longest):
            longest = current
        current = [arr[i]]
print("longest:", longest)

longest: [1, 2, 3]


In [307]:
# 49.Implement matrix multiplication using 2D arrays
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr*2)

[[ 2  4  6]
 [ 8 10 12]]


    NUMPY TASK

In [308]:
# 1.Create a 1D NumPy array of numbers from 0 to 9.
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)

[1 2 3 4 5 6 7 8]


In [309]:
# 2. Create a 1D NumPy array of all even numbers from 2 to 20
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
for num in arr:
    if num % 2==0:
        print(num, end=" ")


2 4 6 8 10 

In [310]:
# 3. Create a 2D NumPy array of shape (3, 3) filled with zeros
import numpy as np 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1 = np.reshape(arr,(3,3))
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [311]:
# 4. Create a 2D NumPy array of shape (4, 4) filled with ones
import numpy as np
arr = np.array([[1,2,3,4],[4,5,6,5],[7,8,9,6],[10,11,12,1]])
arr1 = np.reshape(arr,(4,4))
print(arr1)

[[ 1  2  3  4]
 [ 4  5  6  5]
 [ 7  8  9  6]
 [10 11 12  1]]


In [312]:
# Which dimation array
import numpy as np
arr1 = np.array([1])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr1.ndim)
print(arr2.shape)
print(arr2.ndim)
print(arr3.ndim)

1
(3, 3)
2
3


In [313]:
# 5. Create a NumPy array filled with a specific number (e.g., 7) of size (3, 3)
import numpy as np
a = np.full((3,3),7)
print(a)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [314]:
# 6. Create an array of numbers between 10 and 50 using np.arange()
import numpy as np
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [315]:
# 7. Create an array of 5 random integers between 1 and 100.
import random
a = np.random.randint(1,100,5)
print(a)

[44 47 72 20 25]


In [316]:
# 8. Create an array of 10 random floats between 0 and 1.
import random 
array = np.random.uniform(0,1,10)
print(array)

[0.41362878 0.33776415 0.26808291 0.61114985 0.28848667 0.10961588
 0.05614659 0.99825119 0.61094701 0.21148763]


In [317]:
# 9. Get the shape, size, and data type of an array.
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
arr1 = np.reshape(array,(3,2))
print(arr1)
print(array.size)
print(array.ndim)
print(type(arr1))

[[1 2]
 [3 4]
 [5 6]]
6
2
<class 'numpy.ndarray'>


In [318]:
# 10. Convert a Python list [1, 2, 3, 4, 5] into a NumPy array.
a1 = [1,2,3,4,5]
import numpy as np
a = np.array(a1)
print(a)

[1 2 3 4 5]


In [319]:
# 11. Access the 2nd element from a 1D array.
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
a = arr.flatten()
print(a)
print(a.ndim)
one_D = arr.reshape(-1)
print(one_D)

2
[1 2 3 4 5 6]
1
[1 2 3 4 5 6]


In [320]:
# 3D element to 1D Array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.ndim)
a1 = arr.reshape(1,12) # 2D Array
print(a1)
print(a1.ndim)
a2 = arr.ravel()
print(a2)
print(a2.ndim)

3
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
2
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [321]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
# twoD = arr.reshape(4,3)
twoD = arr.reshape(2,6)
print(twoD)
print(twoD.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
2


In [322]:
# 12. Slice the first 3 elements from a 1D array.
import numpy as np
a1 = np.array([4,6,8,3,1,9,0])
print(a1[:3])

[4 6 8]


In [323]:
# 13. Create a 2D array and access a specific row and column........
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [324]:
# 14. Reverse a 1D NumPy array
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr[::-1])

[6 5 4 3 2 1]


In [325]:
# 15. Create a 3x3 identity matrix.
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.ndim)

3


In [326]:
# 16. Find the maximum and minimum value in a NumPy array.
import numpy as np
arr = np.array([[[4,8,11],[12,6,47]],[[37,3,9],[10,21,34]]])
maximum = np.max(arr)
minimum = np.min(arr)
print(maximum)
print(minimum)

47
3


In [327]:
# 17. Find the sum of all elements in a NumPy array.
Total = sum(arr)
print(Total)


[[41 11 20]
 [22 27 81]]


In [328]:
# 18. Calculate the mean, median, and standard deviation of an array
a1 = np.mean(arr)
a2 = np.median(arr)
a3 = np.std(arr)
print(a1)
print(a2)
print(a3)

16.833333333333332
10.5
13.981138087517131


In [329]:
# 19. Multiply all elements of an array by 2 using broadcasting
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]]])
print(arr*2)

[[[ 2  4  6]
  [ 8 10 12]]]


In [330]:
# 20. Create two arrays and perform element-wise addition, subtraction, multiplication,and division
import numpy 
arr1 = np.array([3,5,8])
arr2 = np.array([4,5,6])
print(arr1 +arr2)
print(arr1 -arr2)
print(arr1 *arr2)
print(arr1 /arr2)


[ 7 10 14]
[-1  0  2]
[12 25 48]
[0.75       1.         1.33333333]


In [331]:
# 21. Create a 1D array of numbers from 0 to 50 and reshape it into a (5, 10) array............
import random
arr = np.random.randint(0,50,size=(5,10))
print(arr)




[[11 11 29 22 40  8 16 26 29 19]
 [30 27  3 21 32 46 39 43 42  1]
 [40  3 20 10 41 17 20 27 32 13]
 [38 42 41  2  7 44 26 39 43 20]
 [43 29 12  1 32  0 35 40 20 46]]


In [332]:
# 22. Flatten a 2D array into a 1D array using ravel() or flatten()
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
a1 = arr.flatten()
a2= arr.ravel()
print(a1)
print(a2)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [333]:
# 23. Create a 4x4 array and extract the last two rows.
import numpy as np
arr = np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
last_row = arr[-2:]
print(last_row)
# print(arr.ndim)



[[ 8  9 10 11]
 [12 13 14 15]]


In [334]:
# 24. Create a 3x3 array and extract the diagonal elements.
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1 = arr.diagonal()
print(a1)

[1 5 9]


In [335]:
# 25. Concatenate two 1D arrays using np.concatenate()
import numpy as np
arr1 = np.array([4,5,6,7])
arr2 = np.array([2,6,9,1])
a1 = np.concatenate((arr1,arr2))
print(a1)

[4 5 6 7 2 6 9 1]


In [336]:
# 26. Stack two 2D arrays vertically and horizontally
import numpy as np
arr1 = np.array([[1,2],[4,5]])
ver = np.vstack(arr1)
hor = np.hstack(arr1)
print(ver)
print(hor)

[[1 2]
 [4 5]]
[1 2 4 5]


In [337]:
# 27. Split an array into equal parts using np.split()
import numpy as np
arr = np.array([1,2,3,4,5,6])
result = np.split(arr,3)
print(result)
    

[array([1, 2]), array([3, 4]), array([5, 6])]


In [338]:
# 28. Replace all elements greater than 10 with 10 in an array.
import numpy as np
arr = np.array([11,4,6,8,9,12,3,15])
arr[arr>10] = 10
print(arr)

[10  4  6  8  9 10  3 10]


In [339]:
# 29. Create a 3x3 matrix and find its transpose().
import numpy as np 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1 = arr.T 
print(a1)
# tran = np.transpose(arr)
# print(tran)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [340]:
# 30. Create two 2D arrays and perform matrix multiplication.
import numpy as np
arr1 = np.array([[2,3,4],[6,7,8]])
arr2 = np.array([[4,6,8],[1,3,5]])
a1 = arr1 * arr2
print(a1)


[[ 8 18 32]
 [ 6 21 40]]


In [341]:
# 31. Create a 3x3 matrix and find its inverse using np.linalg.inv().

metrix = np.array([
    [2,3,4],
    [6,7,8],
    [1,2,3]
])
# a = np.linalg.inv(metrix)
print(a)

[1 2 3 4 5 6]


In [343]:
# 32. Create a 3x3 matrix and find its determinant using np.linalg.det().
metrix = np.array([
    [10,34,5],[22,90,3],[32,56,78]
])
a = np.linalg.det(metrix)
print(a)

5200.000000000001


In [ ]:
# 33. Sort a NumPy array in ascending and descending order.
#sort mines ascending order
import numpy as np
arr = np.array([5,8,1,2,3,0,9])
AS = np.sort(arr)
print(AS)
DAS = np.sort(arr)[::-1]
print(DAS)



[0 1 2 3 5 8 9]
[9 8 5 3 2 1 0]


In [ ]:
# 34. Find unique elements in an array using np.unique().
import numpy as np
arr = np.array([2,4,6,8,9,2,4,6,8,1,1,1,1])
result = np.unique(arr)
print(result)

[1 2 4 6 8 9]


In [ ]:
# 35. Use boolean indexing to extract elements greater than a certain value
import numpy as np
arr = np.array([23,56,12,3,56,7])
result = arr[arr > 10]
print(result)


[23 56 12 56]


In [ ]:
# 36. Create an array and reshape it dynamically using reshape(-1, 1)
import numpy as np
arr = np.array([1,4,6,7,9,1,4,6,10])
a = arr.reshape(-1,1)
print(a)

[[ 1]
 [ 4]
 [ 6]
 [ 7]
 [ 9]
 [ 1]
 [ 4]
 [ 6]
 [10]]


In [ ]:
# 37. Create two arrays and find their element-wise power (a ** b).
import numpy as np 
a1 = np.array([2,5,7])
a2 = np.array([2,2,3])
result  = (a1 ** a2)
print(result)


[  4  25 343]


In [ ]:
# 38. Create two arrays and find their dot product.
import numpy as np 
arr1 = np.array([1,2,3])
arr2 = np.array([5,6,7])
result = np.dot(arr1,arr2)
print(result)
# (1x5)+(2x6)+(3x7)= 38

38


In [ ]:
# 39. Generate a random 3x3 array and normalize it (values between 0 and 1)
import random
result = np.random.random(size=(3,3))
print(result)

[[0.38122071 0.57132817 0.81265983]
 [0.41612458 0.19152823 0.58785691]
 [0.36637326 0.62055451 0.94495173]]


In [ ]:
# 40. Create a 2D array and replace all even numbers with 0 using slicing and conditions.
import numpy as np
arr = np.array([[9,12,4],[2,5,6]])
arr[arr%2==0] = 0
print(arr)

[[9 0 0]
 [0 5 0]]
